language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
  - mongodb
before_script:
  - cp config-travis.parameters.json config.parameters.json
  - npm install --dev
script: npm test
