web:
  build: .
  #command: "bash"
  links:
    - mongo:mongo
  ports:
   - "80:3000"
  volumes_from:
   - data
mongo:
  image: mongo:2.4
  ports:
    - 27017:27017
    - 28017:28017
  volumes:
    - /var/mongo-data:/data/db
data:
  image: magiccyril/data
  volumes:
     - .:/data
